/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.sample

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println("args: ${args.joinToString(", ")}")
    println(Library().someMessage())
}
