/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.sample

class Library {

    fun someLibraryMethod() : Boolean {
        return true
    }

    fun someMessage(): String {
        return "请开始你的表演 !!!"
    }
}
