/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.entrypoint

import sz.scaffold.tools.logger.Logger

fun main(args: Array<String>) {
    Logger.debug("Hello cli app.")
}
