/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.sample

import com.github.ajalt.clikt.core.CliktCommand
import sz.scaffold.tools.logger.Logger

/**
 * Clikt (pronounced “clicked”) is a Kotlin library that makes writing command line interfaces simple and intuitive.
 * It is the “Command Line Interface for Kotlin”.
 * ref: https://ajalt.github.io/clikt/
 */
class Hello : CliktCommand() {
    override fun run() {
        echo("Hello World!")
    }
}

object CliApp {

    @JvmStatic
    fun main(args: Array<String>) {
        Logger.info("args: [${args.joinToString(", ")}]")
        Hello().main(args)
    }

}