/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

plugins {
    java
}

allprojects {

}

dependencies {
    implementation(project(":api_server"))
    implementation(project(":async_task_server"))
}