/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm").version("1.3.50").apply(false)
}

allprojects {

}

tasks.register<Delete>("removeLocalSzJarsCache") {
    val localMaven = this.project.repositories.mavenLocal()
    val path = localMaven.url.path + listOf("com", "github", "kklongming").joinToString(separator = File.separator)
    this.delete(path)
    println("remove Local Maven Cache For Sz Framework: $path")
    val gradleJsrCachePath = listOf(this.project.gradle.gradleUserHomeDir.path, "caches", "modules-2", "files-2.1", "com.github.kklongming").joinToString(separator = File.separator)
    val gradleMetaCachePath1 = listOf(this.project.gradle.gradleUserHomeDir.path, "caches", "modules-2", "metadata-2.23", "descriptors", "com.github.kklongming").joinToString(separator = File.separator)
    val gradleMetaCachePath2 = listOf(this.project.gradle.gradleUserHomeDir.path, "caches", "modules-2", "metadata-2.71", "descriptors", "com.github.kklongming").joinToString(separator = File.separator)
    this.delete(gradleJsrCachePath, gradleMetaCachePath1, gradleMetaCachePath2)
    println("remove Local Gradle Cache For Sz Framework: $gradleJsrCachePath")
}