/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.sample

import com.examples.GreeterGrpc
import com.examples.HelloRequest
import io.grpc.ManagedChannelBuilder
import io.vertx.grpc.VertxChannelBuilder
import sz.scaffold.Application
import sz.scaffold.tools.logger.Logger
import java.util.concurrent.ForkJoinPool

object ClientApp {

    @JvmStatic
    fun main(args: Array<String>) {

        test2()
    }

    private fun test1() {
        val builder = ManagedChannelBuilder.forAddress("localhost", 8888)
            .usePlaintext()

        val channel = builder.build()
        val blockClient = GreeterGrpc.newBlockingStub(channel)
        val client = GreeterGrpc.newFutureStub(channel)


        val request = HelloRequest.newBuilder().setName("帅哥").build()
        val future = client.sayHello(request)

        future.addListener(Runnable {
            Logger.debug("==> is done: ${future.isDone}")
            Logger.debug("==> msg: ${future.get().message}")
        }, ForkJoinPool.commonPool())


        val response = blockClient.sayHello(request)

        Logger.debug("response: ${response.toString()}")
        Logger.debug("response msg: ${response.message}")
    }

    private fun test2() {
        Application.setupVertx()
        val channel = VertxChannelBuilder.forAddress(Application.vertx, "localhost", 8888)
            .usePlaintext()
            .build()

        val client = GreeterGrpc.newVertxStub(channel)

        val request = HelloRequest.newBuilder().setName("帅哥").build()
        client.sayHello(request) {ar ->
            if (ar.succeeded()) {
                Logger.debug("response msg: ${ar.result().message}")
            } else {
                Logger.debug("Rpc call faild: ${ar.cause().message}")
            }
        }
    }
}


