/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.sz.rsatool

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.subcommands
import com.sz.rsatool.commands.CreateKeyPair
import com.sz.rsatool.commands.DecryptText
import com.sz.rsatool.commands.EncryptText

@Suppress("ClassName")
class szRsaTool: CliktCommand(name = "szRsaTool") {
    override fun run() = Unit
}

fun main(args: Array<String>) {
    szRsaTool().subcommands(CreateKeyPair(), DecryptText(), EncryptText()).main(args)
}
